export interface User {
  id: number;
  username: string;
  name: string;
  nickname: string;
  age: number;
  gender: string;
  nationality: string;
  hobby: string;
  email: string;
  address: string;
  registerDate: string;
  password: string;
  role: "user" | "admin";
}

export type UserWithoutPassword = Omit<User, "password">;

export const users: User[] = [
  {
    id: 1,
    username: "johndoe",
    name: "John Doe",
    nickname: "Johnny",
    age: 30,
    gender: "Male",
    nationality: "American",
    hobby: "Photography",
    email: "john.doe@example.com",
    address: "1234 Elm Street",
    registerDate: "2023-01-15",
    password: "password123",
    role: "user",
  },
  {
    id: 2,
    username: "janesmith",
    name: "Jane Smith",
    nickname: "Janey",
    age: 45,
    gender: "Female",
    nationality: "British",
    hobby: "Cooking",
    email: "jane.smith@example.com",
    address: "4321 Oak Avenue",
    registerDate: "2023-02-12",
    password: "password456",
    role: "user",
  },
  {
    id: 3,
    username: "adminuser1",
    name: "Admin One",
    nickname: "Admin",
    age: 50,
    gender: "Female",
    nationality: "Canadian",
    hobby: "Reading",
    email: "admin1@example.com",
    address: "5678 Maple Street",
    registerDate: "2022-12-10",
    password: "adminpassword1",
    role: "admin",
  },
  {
    id: 4,
    username: "mikebrown",
    name: "Mike Brown",
    nickname: "Mikey",
    age: 28,
    gender: "Male",
    nationality: "Australian",
    hobby: "Gaming",
    email: "mike.brown@example.com",
    address: "2345 Pine Road",
    registerDate: "2023-05-21",
    password: "gamer123",
    role: "user",
  },
  {
    id: 5,
    username: "lisawhite",
    name: "Lisa White",
    nickname: "L",
    age: 35,
    gender: "Female",
    nationality: "German",
    hobby: "Cycling",
    email: "lisa.white@example.com",
    address: "9876 Birch Lane",
    registerDate: "2023-06-11",
    password: "cyclelife",
    role: "user",
  },
  {
    id: 6,
    username: "adminuser2",
    name: "Admin Two",
    nickname: "Boss",
    age: 60,
    gender: "Male",
    nationality: "American",
    hobby: "Fishing",
    email: "admin2@example.com",
    address: "8901 River Road",
    registerDate: "2023-01-01",
    password: "adminpassword2",
    role: "admin",
  },
  {
    id: 7,
    username: "karenlee",
    name: "Karen Lee",
    nickname: "Kari",
    age: 40,
    gender: "Female",
    nationality: "Singaporean",
    hobby: "Yoga",
    email: "karen.lee@example.com",
    address: "3456 Jasmine Street",
    registerDate: "2022-11-30",
    password: "yogaflow",
    role: "user",
  },
  {
    id: 8,
    username: "sambaker",
    name: "Sam Baker",
    nickname: "Sammy",
    age: 22,
    gender: "Male",
    nationality: "Indian",
    hobby: "Chess",
    email: "sam.baker@example.com",
    address: "1234 Palm Avenue",
    registerDate: "2023-08-15",
    password: "checkmate2023",
    role: "user",
  },
  {
    id: 9,
    username: "alicerose",
    name: "Alice Rose",
    nickname: "Ali",
    age: 27,
    gender: "Female",
    nationality: "Irish",
    hobby: "Hiking",
    email: "alice.rose@example.com",
    address: "6789 Elmwood Street",
    registerDate: "2023-09-05",
    password: "mountainlover",
    role: "user",
  },
  {
    id: 10,
    username: "markyoung",
    name: "Mark Young",
    nickname: "Marky",
    age: 33,
    gender: "Male",
    nationality: "New Zealander",
    hobby: "Music",
    email: "mark.young@example.com",
    address: "7890 Willow Crescent",
    registerDate: "2023-04-01",
    password: "musicman",
    role: "user",
  },
  {
    id: 11,
    username: "adminuser3",
    name: "Admin Three",
    nickname: "Head",
    age: 55,
    gender: "Female",
    nationality: "South African",
    hobby: "Travel",
    email: "admin3@example.com",
    address: "5672 Oakwood Drive",
    registerDate: "2022-10-12",
    password: "adminpassword3",
    role: "admin",
  },
  {
    id: 12,
    username: "nancyjohnson",
    name: "Nancy Johnson",
    nickname: "Nan",
    age: 38,
    gender: "Female",
    nationality: "French",
    hobby: "Skiing",
    email: "nancy.johnson@example.com",
    address: "1256 Cedar Street",
    registerDate: "2023-07-22",
    password: "snowlover",
    role: "user",
  },
  {
    id: 13,
    username: "williamhall",
    name: "William Hall",
    nickname: "Will",
    age: 65,
    gender: "Male",
    nationality: "American",
    hobby: "Golf",
    email: "william.hall@example.com",
    address: "9081 Sycamore Avenue",
    registerDate: "2022-09-15",
    password: "golfpro",
    role: "user",
  },
  {
    id: 14,
    username: "oliviaturner",
    name: "Olivia Turner",
    nickname: "Liv",
    age: 29,
    gender: "Female",
    nationality: "Brazilian",
    hobby: "Dance",
    email: "olivia.turner@example.com",
    address: "3245 Fir Street",
    registerDate: "2023-02-10",
    password: "dancequeen",
    role: "user",
  },
  {
    id: 15,
    username: "ethanjames",
    name: "Ethan James",
    nickname: "EJ",
    age: 20,
    gender: "Male",
    nationality: "Mexican",
    hobby: "Basketball",
    email: "ethan.james@example.com",
    address: "5467 Redwood Road",
    registerDate: "2023-03-23",
    password: "hooper2023",
    role: "user",
  },
  {
    id: 16,
    username: "charlotteking",
    name: "Charlotte King",
    nickname: "Charlie",
    age: 32,
    gender: "Female",
    nationality: "Swedish",
    hobby: "Running",
    email: "charlotte.king@example.com",
    address: "7891 Pine Avenue",
    registerDate: "2023-07-01",
    password: "runnershigh",
    role: "user",
  },
  {
    id: 17,
    username: "henrywalker",
    name: "Henry Walker",
    nickname: "Hank",
    age: 61,
    gender: "Male",
    nationality: "Dutch",
    hobby: "Woodworking",
    email: "henry.walker@example.com",
    address: "2453 Magnolia Street",
    registerDate: "2022-08-21",
    password: "woodcraft",
    role: "user",
  },
  {
    id: 18,
    username: "sophiamorgan",
    name: "Sophia Morgan",
    nickname: "Sophie",
    age: 24,
    gender: "Female",
    nationality: "Australian",
    hobby: "Swimming",
    email: "sophia.morgan@example.com",
    address: "7564 Pinehurst Lane",
    registerDate: "2023-06-14",
    password: "waterlover",
    role: "user",
  },
  {
    id: 19,
    username: "jackwilson",
    name: "Jack Wilson",
    nickname: "Jacky",
    age: 52,
    gender: "Male",
    nationality: "American",
    hobby: "Gardening",
    email: "jack.wilson@example.com",
    address: "3458 Birchwood Circle",
    registerDate: "2023-05-18",
    password: "greenfingers",
    role: "user",
  },
  {
    id: 20,
    username: "emilyclark",
    name: "Emily Clark",
    nickname: "Em",
    age: 31,
    gender: "Female",
    nationality: "Irish",
    hobby: "Painting",
    email: "emily.clark@example.com",
    address: "1259 Cedarwood Avenue",
    registerDate: "2023-07-20",
    password: "artlover2023",
    role: "user",
  },
  {
    id: 21,
    username: "lukebennett",
    name: "Luke Bennett",
    nickname: "Lukey",
    age: 43,
    gender: "Male",
    nationality: "British",
    hobby: "Football",
    email: "luke.bennett@example.com",
    address: "2345 Cypress Drive",
    registerDate: "2023-02-28",
    password: "goalkeeper123",
    role: "user",
  },
  {
    id: 22,
    username: "sarahroberts",
    name: "Sarah Roberts",
    nickname: "Sare",
    age: 26,
    gender: "Female",
    nationality: "Canadian",
    hobby: "Baking",
    email: "sarah.roberts@example.com",
    address: "6789 Birchwood Lane",
    registerDate: "2023-03-19",
    password: "sweettooth",
    role: "user",
  },
  {
    id: 23,
    username: "michaelhughes",
    name: "Michael Hughes",
    nickname: "Mick",
    age: 59,
    gender: "Male",
    nationality: "Irish",
    hobby: "Fishing",
    email: "michael.hughes@example.com",
    address: "3421 Maple Avenue",
    registerDate: "2023-04-10",
    password: "angler59",
    role: "user",
  },
  {
    id: 24,
    username: "jessicawood",
    name: "Jessica Wood",
    nickname: "Jess",
    age: 35,
    gender: "Female",
    nationality: "Australian",
    hobby: "Surfing",
    email: "jessica.wood@example.com",
    address: "5682 Coral Road",
    registerDate: "2023-05-05",
    password: "surfinglife",
    role: "user",
  },
  {
    id: 25,
    username: "tomphillips",
    name: "Tom Phillips",
    nickname: "Tommy",
    age: 48,
    gender: "Male",
    nationality: "New Zealander",
    hobby: "Tennis",
    email: "tom.phillips@example.com",
    address: "8723 Willow Street",
    registerDate: "2023-06-18",
    password: "tennispro",
    role: "user",
  },
  {
    id: 26,
    username: "chloebrown",
    name: "Chloe Brown",
    nickname: "Chlo",
    age: 28,
    gender: "Female",
    nationality: "French",
    hobby: "Yoga",
    email: "chloe.brown@example.com",
    address: "1256 Cedar Street",
    registerDate: "2023-07-24",
    password: "yogalover",
    role: "user",
  },
  {
    id: 27,
    username: "danielmorris",
    name: "Daniel Morris",
    nickname: "Dan",
    age: 39,
    gender: "Male",
    nationality: "South African",
    hobby: "Running",
    email: "daniel.morris@example.com",
    address: "4567 Oakwood Drive",
    registerDate: "2023-01-29",
    password: "runfast39",
    role: "user",
  },
  {
    id: 28,
    username: "laurathompson",
    name: "Laura Thompson",
    nickname: "Laurie",
    age: 52,
    gender: "Female",
    nationality: "German",
    hobby: "Gardening",
    email: "laura.thompson@example.com",
    address: "6742 Pine Road",
    registerDate: "2023-03-21",
    password: "greenfingers52",
    role: "user",
  },
  {
    id: 29,
    username: "davidwilson",
    name: "David Wilson",
    nickname: "Dave",
    age: 18,
    gender: "Male",
    nationality: "American",
    hobby: "Video Games",
    email: "david.wilson@example.com",
    address: "7891 Oakwood Lane",
    registerDate: "2023-08-02",
    password: "gamerlife18",
    role: "user",
  },
  {
    id: 30,
    username: "meganmartin",
    name: "Megan Martin",
    nickname: "Meg",
    age: 21,
    gender: "Female",
    nationality: "Mexican",
    hobby: "Drawing",
    email: "megan.martin@example.com",
    address: "3425 Sycamore Avenue",
    registerDate: "2023-05-10",
    password: "artistatheart",
    role: "user",
  },
  {
    id: 31,
    username: "stevecollins",
    name: "Steve Collins",
    nickname: "Stevie",
    age: 42,
    gender: "Male",
    nationality: "British",
    hobby: "Photography",
    email: "steve.collins@example.com",
    address: "2456 Maple Street",
    registerDate: "2023-07-15",
    password: "clickclick42",
    role: "user",
  },
  {
    id: 32,
    username: "oliverroberts",
    name: "Oliver Roberts",
    nickname: "Ollie",
    age: 37,
    gender: "Male",
    nationality: "New Zealander",
    hobby: "Cricket",
    email: "oliver.roberts@example.com",
    address: "8765 Birch Street",
    registerDate: "2023-04-25",
    password: "batsman37",
    role: "user",
  },
  {
    id: 33,
    username: "abbyscott",
    name: "Abby Scott",
    nickname: "Abs",
    age: 31,
    gender: "Female",
    nationality: "Australian",
    hobby: "Hiking",
    email: "abby.scott@example.com",
    address: "1346 Cypress Lane",
    registerDate: "2023-02-11",
    password: "trailblazer",
    role: "user",
  },
  {
    id: 34,
    username: "matthewwright",
    name: "Matthew Wright",
    nickname: "Matt",
    age: 56,
    gender: "Male",
    nationality: "Irish",
    hobby: "Cycling",
    email: "matthew.wright@example.com",
    address: "5687 Cedarwood Lane",
    registerDate: "2023-08-27",
    password: "pedalpower",
    role: "user",
  },
  {
    id: 35,
    username: "isabellamoore",
    name: "Isabella Moore",
    nickname: "Bella",
    age: 24,
    gender: "Female",
    nationality: "British",
    hobby: "Running",
    email: "isabella.moore@example.com",
    address: "9342 Redwood Road",
    registerDate: "2023-03-05",
    password: "runnershigh24",
    role: "user",
  },
  {
    id: 36,
    username: "joshuamorgan",
    name: "Joshua Morgan",
    nickname: "Josh",
    age: 62,
    gender: "Male",
    nationality: "Canadian",
    hobby: "Cooking",
    email: "joshua.morgan@example.com",
    address: "4502 Cypress Road",
    registerDate: "2023-06-02",
    password: "masterchef62",
    role: "user",
  },
  {
    id: 37,
    username: "amandaparker",
    name: "Amanda Parker",
    nickname: "Mandy",
    age: 27,
    gender: "Female",
    nationality: "French",
    hobby: "Traveling",
    email: "amanda.parker@example.com",
    address: "7845 Maple Drive",
    registerDate: "2023-07-19",
    password: "travellife27",
    role: "user",
  },
  {
    id: 38,
    username: "zacharyevans",
    name: "Zachary Evans",
    nickname: "Zach",
    age: 53,
    gender: "Male",
    nationality: "American",
    hobby: "Golf",
    email: "zachary.evans@example.com",
    address: "3429 Oakwood Avenue",
    registerDate: "2023-08-01",
    password: "golfer53",
    role: "user",
  },
  {
    id: 39,
    username: "hannahlawrence",
    name: "Hannah Lawrence",
    nickname: "Hannie",
    age: 34,
    gender: "Female",
    nationality: "South African",
    hobby: "Swimming",
    email: "hannah.lawrence@example.com",
    address: "1783 Cypress Crescent",
    registerDate: "2023-09-03",
    password: "waterbaby34",
    role: "user",
  },
  {
    id: 40,
    username: "nathansmith",
    name: "Nathan Smith",
    nickname: "Nate",
    age: 45,
    gender: "Male",
    nationality: "Canadian",
    hobby: "Chess",
    email: "nathan.smith@example.com",
    address: "9084 Walnut Street",
    registerDate: "2023-05-14",
    password: "chessmaster45",
    role: "user",
  },
  {
    id: 41,
    username: "emilyturner",
    name: "Emily Turner",
    nickname: "Em",
    age: 23,
    gender: "Female",
    nationality: "Australian",
    hobby: "Photography",
    email: "emily.turner@example.com",
    address: "4563 Willow Lane",
    registerDate: "2023-08-22",
    password: "shutterbug23",
    role: "user",
  },
  {
    id: 42,
    username: "johnwalker",
    name: "John Walker",
    nickname: "Johnny",
    age: 61,
    gender: "Male",
    nationality: "British",
    hobby: "Golf",
    email: "john.walker@example.com",
    address: "7124 Pine Avenue",
    registerDate: "2023-06-17",
    password: "golflife61",
    role: "user",
  },
];
