export interface User {
  id: number;
  username: string;
  name: string;
  nickname: string;
  age: number;
  gender: string;
  nationality: string;
  hobby: string;
  email: string;
  address: string;
  registerDate: string;
}

export const users: User[] = [
  {
    id: 1,
    username: "johndoe",
    name: "John Doe",
    nickname: "Johnny",
    age: 30,
    gender: "Male",
    nationality: "American",
    hobby: "Photography",
    email: "johndoe@example.com",
    address: "123 Main St, Anytown, USA",
    registerDate: "2024-01-15",
  },
  {
    id: 2,
    username: "janedoe",
    name: "Jane Doe",
    nickname: "Janey",
    age: 28,
    gender: "Female",
    nationality: "Canadian",
    hobby: "Cycling",
    email: "janedoe@example.com",
    address: "456 Elm St, Somewhere, Canada",
    registerDate: "2024-02-20",
  },
  {
    id: 3,
    username: "samsmith",
    name: "Sam Smith",
    nickname: "Sammers",
    age: 35,
    gender: "Non-binary",
    nationality: "British",
    hobby: "Cooking",
    email: "samsmith@example.com",
    address: "789 Oak St, London, UK",
    registerDate: "2024-03-10",
  },
  {
    id: 4,
    username: "emilyjohnson",
    name: "Emily Johnson",
    nickname: "Em",
    age: 25,
    gender: "Female",
    nationality: "Australian",
    hobby: "Reading",
    email: "emilyjohnson@example.com",
    address: "321 Pine St, Sydney, Australia",
    registerDate: "2024-04-05",
  },
  {
    id: 5,
    username: "michaelbrown",
    name: "Michael Brown",
    nickname: "Mike",
    age: 40,
    gender: "Male",
    nationality: "New Zealander",
    hobby: "Fishing",
    email: "michaelbrown@example.com",
    address: "654 Maple St, Auckland, NZ",
    registerDate: "2024-05-12",
  },
  {
    id: 6,
    username: "sarahconnor",
    name: "Sarah Connor",
    nickname: "Sari",
    age: 32,
    gender: "Female",
    nationality: "German",
    hobby: "Hiking",
    email: "sarahconnor@example.com",
    address: "987 Birch St, Berlin, Germany",
    registerDate: "2024-06-18",
  },
  {
    id: 7,
    username: "davidlee",
    name: "David Lee",
    nickname: "Dave",
    age: 29,
    gender: "Male",
    nationality: "Chinese",
    hobby: "Gaming",
    email: "davidlee@example.com",
    address: "234 Cedar St, Beijing, China",
    registerDate: "2024-07-25",
  },
  {
    id: 8,
    username: "lisaadams",
    name: "Lisa Adams",
    nickname: "Liz",
    age: 27,
    gender: "Female",
    nationality: "Japanese",
    hobby: "Gardening",
    email: "lisaadams@example.com",
    address: "567 Willow St, Tokyo, Japan",
    registerDate: "2024-08-30",
  },
  {
    id: 9,
    username: "robertmartin",
    name: "Robert Martin",
    nickname: "Rob",
    age: 38,
    gender: "Male",
    nationality: "French",
    hobby: "Traveling",
    email: "robertmartin@example.com",
    address: "890 Chestnut St, Paris, France",
    registerDate: "2024-09-14",
  },
  {
    id: 10,
    username: "karenwilson",
    name: "Karen Wilson",
    nickname: "Kari",
    age: 31,
    gender: "Female",
    nationality: "Italian",
    hobby: "Painting",
    email: "karenwilson@example.com",
    address: "1234 Oak St, Rome, Italy",
    registerDate: "2024-10-02",
  },
  {
    id: 11,
    username: "paulwhite",
    name: "Paul White",
    nickname: "Paulie",
    age: 45,
    gender: "Male",
    nationality: "American",
    hobby: "Writing",
    email: "paulwhite@example.com",
    address: "567 Elm St, New York, USA",
    registerDate: "2024-01-23",
  },
  {
    id: 12,
    username: "lucasgarcia",
    name: "Lucas Garcia",
    nickname: "Luke",
    age: 22,
    gender: "Male",
    nationality: "Spanish",
    hobby: "Swimming",
    email: "lucasgarcia@example.com",
    address: "234 Pine St, Madrid, Spain",
    registerDate: "2024-02-14",
  },
  {
    id: 13,
    username: "miawong",
    name: "Mia Wong",
    nickname: "Mia",
    age: 26,
    gender: "Female",
    nationality: "Hong Konger",
    hobby: "Dancing",
    email: "miawong@example.com",
    address: "789 Maple St, Hong Kong",
    registerDate: "2024-03-29",
  },
  {
    id: 14,
    username: "kevinroberts",
    name: "Kevin Roberts",
    nickname: "Kev",
    age: 50,
    gender: "Male",
    nationality: "British",
    hobby: "Golf",
    email: "kevinroberts@example.com",
    address: "321 Willow St, Manchester, UK",
    registerDate: "2024-04-18",
  },
  {
    id: 15,
    username: "angelaanderson",
    name: "Angela Anderson",
    nickname: "Angie",
    age: 33,
    gender: "Female",
    nationality: "Australian",
    hobby: "Surfing",
    email: "angelaanderson@example.com",
    address: "456 Cedar St, Brisbane, Australia",
    registerDate: "2024-05-11",
  },
  {
    id: 16,
    username: "josephmiller",
    name: "Joseph Miller",
    nickname: "Joe",
    age: 41,
    gender: "Male",
    nationality: "Canadian",
    hobby: "Music",
    email: "josephmiller@example.com",
    address: "789 Birch St, Toronto, Canada",
    registerDate: "2024-06-22",
  },
  {
    id: 17,
    username: "oliviajones",
    name: "Olivia Jones",
    nickname: "Liv",
    age: 24,
    gender: "Female",
    nationality: "American",
    hobby: "Skiing",
    email: "oliviajones@example.com",
    address: "234 Oak St, Los Angeles, USA",
    registerDate: "2024-07-03",
  },
  {
    id: 18,
    username: "jamesmartin",
    name: "James Martin",
    nickname: "Jim",
    age: 37,
    gender: "Male",
    nationality: "French",
    hobby: "Photography",
    email: "jamesmartin@example.com",
    address: "567 Chestnut St, Lyon, France",
    registerDate: "2024-08-16",
  },
  {
    id: 19,
    username: "lilitharenson",
    name: "Lilith Arenson",
    nickname: "Lily",
    age: 29,
    gender: "Female",
    nationality: "German",
    hobby: "Traveling",
    email: "lilitharenson@example.com",
    address: "890 Oak St, Berlin, Germany",
    registerDate: "2024-09-05",
  },
  {
    id: 20,
    username: "maxkeller",
    name: "Max Keller",
    nickname: "Max",
    age: 47,
    gender: "Male",
    nationality: "Swiss",
    hobby: "Cycling",
    email: "maxkeller@example.com",
    address: "123 Maple St, Zurich, Switzerland",
    registerDate: "2024-10-21",
  },
  {
    id: 21,
    username: "nataliesmith",
    name: "Natalie Smith",
    nickname: "Nat",
    age: 31,
    gender: "Female",
    nationality: "American",
    hobby: "Cooking",
    email: "nataliesmith@example.com",
    address: "456 Birch St, Boston, USA",
    registerDate: "2024-01-30",
  },
  {
    id: 22,
    username: "andrewthomas",
    name: "Andrew Thomas",
    nickname: "Andy",
    age: 29,
    gender: "Male",
    nationality: "Canadian",
    hobby: "Running",
    email: "andrewthomas@example.com",
    address: "789 Cedar St, Vancouver, Canada",
    registerDate: "2024-02-25",
  },
  {
    id: 23,
    username: "juliaharper",
    name: "Julia Harper",
    nickname: "Jules",
    age: 26,
    gender: "Female",
    nationality: "British",
    hobby: "Yoga",
    email: "juliaharper@example.com",
    address: "234 Elm St, Edinburgh, UK",
    registerDate: "2024-03-22",
  },
  {
    id: 24,
    username: "ethangreen",
    name: "Ethan Green",
    nickname: "Ethan",
    age: 33,
    gender: "Male",
    nationality: "Australian",
    hobby: "Surfing",
    email: "ethangreen@example.com",
    address: "567 Pine St, Perth, Australia",
    registerDate: "2024-04-15",
  },
  {
    id: 25,
    username: "rachelmoore",
    name: "Rachel Moore",
    nickname: "Rach",
    age: 40,
    gender: "Female",
    nationality: "New Zealander",
    hobby: "Gardening",
    email: "rachelmoore@example.com",
    address: "890 Cedar St, Wellington, NZ",
    registerDate: "2024-05-30",
  },
  {
    id: 26,
    username: "nathanperez",
    name: "Nathan Perez",
    nickname: "Nate",
    age: 22,
    gender: "Male",
    nationality: "Mexican",
    hobby: "Video Games",
    email: "nathanperez@example.com",
    address: "123 Birch St, Mexico City, Mexico",
    registerDate: "2024-06-10",
  },
  {
    id: 27,
    username: "sophietaylor",
    name: "Sophie Taylor",
    nickname: "Sophie",
    age: 28,
    gender: "Female",
    nationality: "American",
    hobby: "Music",
    email: "sophietaylor@example.com",
    address: "456 Oak St, San Francisco, USA",
    registerDate: "2024-07-20",
  },
  {
    id: 28,
    username: "alexjohnson",
    name: "Alex Johnson",
    nickname: "Alex",
    age: 31,
    gender: "Non-binary",
    nationality: "Canadian",
    hobby: "Cooking",
    email: "alexjohnson@example.com",
    address: "789 Maple St, Toronto, Canada",
    registerDate: "2024-08-25",
  },
  {
    id: 29,
    username: "emmaclark",
    name: "Emma Clark",
    nickname: "Em",
    age: 27,
    gender: "Female",
    nationality: "American",
    hobby: "Hiking",
    email: "emmaclark@example.com",
    address: "321 Elm St, Seattle, USA",
    registerDate: "2024-09-12",
  },
  {
    id: 30,
    username: "jackmiller",
    name: "Jack Miller",
    nickname: "Jack",
    age: 36,
    gender: "Male",
    nationality: "British",
    hobby: "Golf",
    email: "jackmiller@example.com",
    address: "654 Oak St, Birmingham, UK",
    registerDate: "2024-10-05",
  },
];
